import Header from '@/components/Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      
      
      <body className={inter.className +" bg-gradient-to-b from-[#000000] to-[#130F40] min-h-screen" }>
        <div className='mt-4' >
        <Header/>
        {children}
        </div>
        </body>
    </html>
  )
}
